// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:5e6cc26d-064e-409a-93da-7afe89022ce9",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_hpemp3loy",
    "aws_user_pools_web_client_id": "41mvqat2hmak6sl4b11g50hhct",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "photowinpictures-dev",
            "region": "eu-central-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "picturesapi",
            "endpoint": "https://dvmcvle4je.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ]
};


export default awsmobile;
